name: CI DevSecOps Chandra

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan Code with SAST
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8


      - name: install Bandit
        run: pip install bandit
        
      - name: Run Bandit Scan
        run : bandit -ll -ii -r . -f json -o chandra-devsecops-report.json # command -ll and -ii untuk memfilter hanya menampilkan report di level medium dan high kerentanan masalaha pada code nya 

      - name: Upload Artifact Report 
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit-findings-chandra
          path: chandra-devsecops-report.json

  images-scan:
    name: Build Images and Scan With Docker Scout
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '20.10.7'

      - name: Docker Build Images
        run: docker build -f Dockerfile -t chandraapp:latest .

      # - name: Docker Scout Scan
      #   run : |
      #     curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
      #     sh install-scout.sh

      #     echo ${{ secrets.REPO_PASSWORD }} | docker login -u ${{ secrets.REPO_USER}} --password-stdin

      #     docker scout quickview
      #     docker scout cves

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.0.9
        with: 
          dockerhub-user: ${{ secrets.REPO_USER}}
          dockerhub-password: ${{ secrets.REPO_PASSWORD }}
          command: quickview, cves